# Generated by Django 5.0.6 on 2026-06-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fuente', models.CharField(choices=[('upload', 'Upload directo'), ('vuelo', 'Imagen de vuelo existente')], default='upload', max_length=10)),
                ('archivo_tiff', models.FileField(blank=True, null=True, upload_to='tiff_uploads/%Y/%m/')),
                ('tile_size', models.IntegerField(default=640, help_text='Tamaño del tile en píxeles (ancho y alto)')),
                ('overlap_px', models.IntegerField(default=64, help_text='Solapamiento entre tiles en píxeles')),
                ('calidad_jpg', models.IntegerField(default=85, help_text='Calidad JPEG (1-100)')),
                ('saltar_vacios', models.BooleanField(default=True, help_text='Ignorar tiles sin contenido (fondo negro > 80%)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('total_tiles', models.IntegerField(default=0)),
                ('tiles_procesados', models.IntegerField(default=0)),
                ('error_mensaje', models.TextField(blank=True)),
                ('directorio_tiles', models.CharField(blank=True, max_length=500)),
                ('archivo_zip', models.FileField(blank=True, null=True, upload_to='zips_tiles/%Y/%m/')),
                ('metadatos_geo', models.JSONField(default=dict)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('imagen_vuelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_conversion', to='vision.imagen')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
