# Generated by Django 5.0.6 on 2026-06-21 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_enable_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Punto geográfico del campo (WGS84)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deteccion',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Posición geográfica del centro de la detección, calculada proyectando coordenadas de píxel sobre el bbox_geo del tile', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroide geográfico del vuelo, extraído del GeoTIFF si está disponible', null=True, srid=4326),
        ),
    ]
