# Generated by Django 5.0.6 on 2026-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_campo_punto_deteccion_ubicacion_vuelo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccion',
            name='origen',
            field=models.CharField(choices=[('modelo', 'Detectada por el modelo'), ('manual', 'Agregada manualmente'), ('corregida', 'Corregida manualmente')], default='modelo', max_length=20),
        ),
        migrations.AddField(
            model_name='imagen',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='revisada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
