# Generated by Django 5.0.6 on 2026-06-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReentrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reentrenar', models.BooleanField(default=True, help_text='Encolar un reentrenamiento al alcanzar el umbral.')),
                ('umbral_correcciones', models.IntegerField(default=50)),
                ('auto_activar_modelo', models.BooleanField(default=True)),
                ('margen_map50', models.FloatField(default=0.0, help_text='mAP50 nuevo debe superar al activo por este margen.')),
                ('epochs', models.IntegerField(default=50)),
                ('base_model', models.CharField(default='yolov8n.pt', max_length=20)),
                ('correcciones_acumuladas', models.IntegerField(default=0)),
                ('ultimo_reentrenamiento', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de reentrenamiento',
                'verbose_name_plural': 'Configuración de reentrenamiento',
            },
        ),
        migrations.CreateModel(
            name='CicloReentrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disparador', models.CharField(choices=[('auto', 'Automático (umbral)'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('construyendo', 'Construyendo dataset'), ('entrenando', 'Entrenando'), ('evaluando', 'Evaluando mejora'), ('activado', 'Completado y activado'), ('completado', 'Completado (no activado)'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('num_correcciones', models.IntegerField(default=0)),
                ('num_imagenes', models.IntegerField(default=0)),
                ('num_anotaciones', models.IntegerField(default=0)),
                ('map50_anterior', models.FloatField(blank=True, null=True)),
                ('map50_nuevo', models.FloatField(blank=True, null=True)),
                ('activado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos', to='training.datasetentrenamiento')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos', to='training.modeloentrenado')),
            ],
            options={
                'verbose_name': 'Ciclo de reentrenamiento',
                'verbose_name_plural': 'Ciclos de reentrenamiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
