# Generated by Django 5.0.6 on 2026-06-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='datasets/%Y/%m/')),
                ('formato', models.CharField(choices=[('yolo', 'YOLO Ultralytics (recomendado)'), ('cvat_xml', 'CVAT for Images 1.1 XML'), ('coco', 'COCO JSON')], default='yolo', max_length=20)),
                ('num_imagenes', models.IntegerField(default=0)),
                ('clases', models.JSONField(default=list)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('validando', 'Validando'), ('valido', 'Válido'), ('invalido', 'Inválido')], default='subido', max_length=20)),
                ('reporte_validacion', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('base_model', models.CharField(choices=[('yolov8n.pt', 'YOLOv8 Nano (más rápido, CPU)'), ('yolov8s.pt', 'YOLOv8 Small'), ('yolov8m.pt', 'YOLOv8 Medium')], default='yolov8n.pt', max_length=20)),
                ('epochs', models.IntegerField(default=50)),
                ('img_size', models.IntegerField(default=640)),
                ('patience', models.IntegerField(default=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando dataset'), ('entrenando', 'Entrenando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('epoca_actual', models.IntegerField(default=0)),
                ('metricas', models.JSONField(default=dict)),
                ('archivo_pesos', models.FileField(blank=True, null=True, upload_to='modelos/')),
                ('activo', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='training.datasetentrenamiento')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
